### ISSUE TITLE
Add database rebuild option to User Tools

### ISSUE THREAD

**Issue by bucanero** [bucanero/apollo-ps4#10]
the database rebuilder script could be part of the "User Tools":
- https://github.com/Zer0xFF/PS4_db_rebuilder
- https://github.com/aizenar/PS4_db_Rebuilder_EXT
- https://github.com/AyAPS/PS4RestoreFPKGdeletion/blob/main/PS4RestoreFPKGdeletion_v1.1.ps1

SFOs and SQLite are already handled by Apollo, so the only thing left is the SQL queries.

**Comment by Pharaoh2k** [comment]
The only database rebuilder that actually works is https://github.com/aizenar/PS4_db_Rebuilder_EXT, for me at least (FW 9.00).
Note that it only works for internal storage and does not cover DLCs. If you can improve the script as well, to include DLCs to addcont.db, that will be awesome. I tried, but have no idea how to distinguish between normal game packages and DLCs, although I am sure there is a way.

P.S. This is a slightly improved private script that also handles more than 500 games (the original aizenar script fails at 500+), courtesy of ctn123:
[code]
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function
from ftplib import FTP
import sqlite3
import appinfo
import io
import os
import re
from sfo.sfo import SfoFile as SfoFile
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("PS4_IP", help="PS4 ftp ip address")
parser.add_argument('--fw', default="6.72", help='currently support 5.05, 6.72')
parser.add_argument('--port', default="2121", help='PS4 FTP Port Number')
args = parser.parse_args()
app_db = "tmp/app.db"
PS4_IP = args.PS4_IP

port = 2121
port = int(args.port)

value_format = ""
if(args.fw == "5.05"):
        value_format = """("%s", "%s", "%s", "/user/appmeta/%s", "2018-07-27 15:06:46.822", "0", "0", "5", "1", "100", "0", "151", "5", "1", "gd", "0", "0", "0", "0", NULL, NULL, NULL, "%d", "2018-07-27 15:06:46.802", "0", "game", NULL, "0", "0", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, "0", NULL, NULL, NULL, NULL, NULL, "0", "0", NULL, "2018-07-27 15:06:46.757")"""
elif(args.fw == "6.72"):
        value_format = """("%s", "%s", "%s", "/user/appmeta/%s", "2018-07-27 15:06:46.822", "0", "0", "5", "1", "100", "0", "151","5", "1", "gd", "0", "0", "0", "0",NULL, NULL, NULL, "%d", "2018-07-27 15:06:46.802", "0", "game", NULL, "0", "0", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, "0", NULL,NULL, NULL, NULL, NULL, "0", "0", NULL, "2018-07-27 15:06:46.757","0","0","0","0","0",NULL)"""
else:
        value_format = """("%s", "%s", "%s", "/user/appmeta/%s", "2018-07-27 15:06:46.822", "0", "0", "5", "1", "100", "0", "151","5", "1", "gd", "0", "0", "0", "0",NULL, NULL, NULL, "%d", "2018-07-27 15:06:46.802", "0", "game", NULL, "0", "0", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, "0", NULL,NULL, NULL, NULL, NULL, "0", "0", NULL, "2018-07-27 15:06:46.757","0","0","0","0","0",NULL)"""

if not os.path.exists('tmp'):
        os.makedirs('tmp')

class CUSA :
        sfo = None
        size = 10000000
        is_usable = False

info = {}
files = []

def sort_files(file) :
        if re.search("^[A-Z]", file[-9]):
                files.append("'%s'" % file[-9:])

def get_game_info_by_id(GameID) :
        if(GameID not in info) :
                info[GameID] = CUSA()

                try:
                        buffer = io.BytesIO()
                        ftp.cwd('/system_data/priv/appmeta/%s/' % GameID)
                        ftp.retrbinary("RETR param.sfo" , buffer.write)
                        buffer.seek(0)
                        sfo = SfoFile.from_reader(buffer)
                        info[GameID].sfo = sfo
                        info[GameID].size = ftp.size("/user/app/%s/app.pkg" % GameID)
                        info[GameID].is_usable = True
                except Exception as e:
                        print("Error processing %s, ignorining..." % GameID)
                        print("type error: " + str(e))

        return info[GameID]

def bin(input, bin_size):
    for i in range(0, len(input), bin_size):
        yield input[i:i + bin_size]


ftp = FTP()
ftp.connect(PS4_IP, port, timeout=30)
ftp.login(user='username', passwd = 'password')
if(len(files) == 0) :
        ftp.cwd('/user/app/')
        ftp.dir(sort_files)
        print(files)


ftp.cwd('/system_data/priv/mms/')
lf = open(app_db, "wb")
ftp.retrbinary("RETR app.db" , lf.write)
lf.close()

conn = sqlite3.connect(app_db)

cursor = conn.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'tbl_appbrowse_%%';")
tables = cursor.fetchall()

for files_subset in bin(files, 500):
        files_joined = "SELECT %s AS titleid " % ' AS titleid UNION SELECT '.join(files_subset)
        tbl_appbrowse = []
        for tbl in tables :
                tbl_appbrowse.append(tbl[0])
                print("Processing table: %s" % tbl[0])
                cursor.execute("SELECT T.titleid FROM (%s) T WHERE T.titleid NOT IN (SELECT titleid FROM %s);" % (files_joined, tbl[0]))
                list_id = cursor.fetchall()
                sql_list = []
                for tmp_GameID in list_id :
                        GameID = tmp_GameID[0].replace("'", "")
                        print(" Processing GameID: %s... " % GameID, end='')
                        cusa = get_game_info_by_id(GameID)
                        if(cusa.is_usable == True) :
                                sql_list.append(value_format
                                        % (cusa.sfo['TITLE_ID'], cusa.sfo['CONTENT_ID'], cusa.sfo['TITLE'], cusa.sfo['TITLE_ID'], cusa.size))
                                print("Completed %d" % cusa.size)
                        else :
                                print("Ignoring")

                if(len(sql_list) > 0) :
                        cursor.execute("INSERT INTO %s VALUES %s;" % (tbl[0], ', '.join(sql_list)))

print('')
print('')
print('')

print("Processing table: tbl_appinfo")

cursor.execute("SELECT DISTINCT T.titleid FROM (SELECT titleid FROM %s) T WHERE T.titleid NOT IN (SELECT DISTINCT titleid FROM tbl_appinfo);" % (" UNION SELECT titleid FROM ".join(tbl_appbrowse)))
missing_appinfo_cusa_id = cursor.fetchall()
for tmp_cusa_id in missing_appinfo_cusa_id :
        game_id = tmp_cusa_id[0]
        print(" Processing GameID: %s... " % game_id, end='')
        cusa = get_game_info_by_id(game_id)
        if(cusa.is_usable == True) :
                sql_items = appinfo.get_pseudo_appinfo(cusa.sfo, cusa.size)
                for key, value in sql_items.items():
                        cursor.execute("INSERT INTO tbl_appinfo (titleid, key, val) VALUES (?, ?, ?);", [game_id, key, value])
                print("Completed")
        else :
                print("Skipped")

conn.commit()

conn.close()

ftp.cwd('/system_data/priv/mms/')
file = open(app_db,'rb')
ftp.storbinary('STOR app.db', file)
file.close()
[/code]

**Comment by bucanero** [comment]
@Pharaoh2k  I was testing the script you posted, and I found some things (after running the script):
- game size is plain wrong when you see the details from XMB (like all games saying 400Gb)
- after you run a game once, the "Delete" option is no longer available

the rest seems ok, homebrew and fpkgs are restored and listed on the XMB. 

About the missing "delete" option, from [some notes on the web](https://gbatemp.net/threads/one-of-a-kind-bug.551318/post-8845285):
> Change the `canRemove` entry for the game from 0 to 1 in the tbl_appbrowse table of the db.

Since I'm already messing up with `app.db` for my own needs, I'll start working on this feature for Apollo.
Even with the current limitations (like wrong game size or missing delete) I think it's an useful feature and once I have that working I'll try to improve it.

**Comment by bucanero** [comment]
fixed in:
- 2d615b1fbf32de918b07f13ceb248c55b43d099f
- 0808a713df70edbca9d3cfb018480b18886b93ac
- c7bbd262f9b243878372ae7134f581e016467c9c
