### ISSUE TITLE
Apollo save tool & Golden Hen Cheat manager = not working + crashed game

### ISSUE THREAD

**Issue by mrkingpin** [bucanero/apollo-ps4#103]
I have a terminator resistance save file I obtained online. Using this tool it works excellent but if I also use the golden hen cheat manager to enable cheats unlimited ammo that it's causing a glitch in the game and crashes shortly after firing a few rounds and unlimited ammo not working either. 

Cheat manager works perfectly on it's own but does not like apollo save tool very much .. lol

If possible would appreciate if you could look into it..

Thank you for all your work

**Comment by bucanero** [comment]
**Never run games while save-game patches are loaded.**
You must exit Apollo properly (by pressing "circle") to remove all save-game patches from memory.

If cheats fail and Apollo is properly unloaded, then the issue is related to the cheat code, and you should contact the cheat creator.
