### ISSUE TITLE
Cannot import retail save data from fw10.01 to 9.00

### ISSUE THREAD

**Issue by IRONB0SS** [bucanero/apollo-ps4#104]
![Apollo Save Tool_20230211175243](https://user-images.githubusercontent.com/97769328/218263142-fbc96b81-14f2-4a58-ac93-b3f451aa3f30.jpg)

I'm trying to import squad save file for FIFA 23

**Comment by IRONB0SS** [comment]
I can remember I could import save files from fw9.60 to 9.00 but 10.01 seems something changed

**Comment by Masamune3210** [comment]
pretty sure that apollo uses a whitelist to handle firmware versions it knows can be handled like that, but I could be wrong and there is always a chance they decided to mess with the save archive format again

**Comment by bucanero** [comment]
Apollo doesn't have a specific check right now, but in any case higher firmware usually changes the encryption keys, so for example a user with 6.72 will never be able to import a 9.0 save. (At least until all the keys are public) 

So this is normal and not a issue with the application.
