### ISSUE TITLE
Change update pkg path to /data/pkg to allow for easier install on latest GoldHen

### ISSUE THREAD

**Issue by Masamune3210** [bucanero/apollo-ps4#107]
If the path the update pkg was downloaded to was changed to /data/pkg instead of just /data, the user would be able to just go to the package installer and install it as long as they are on the latest version of goldhen

**Comment by Masamune3210** [comment]
Just realized that this sounds like a demand, I promise you I do not mean it as such. I tried to make a pull request to do it myself but....it didn't go so well

**Comment by bucanero** [comment]
For backwards compatibility, I'll probably check if `/data/pkg` folder exists, then use it. If not, then download to `/data` as usual.

I also need to test the integration with the HB Store API. That would also allow to update the app using the homebrew store app if the user has it installed.

**Comment by bucanero** [comment]
fixed in 332343984852a67f40ecdc721030fb1004cb89cd
