### ISSUE TITLE
Support importing encrypted save-games

### ISSUE THREAD

**Issue by ToniFabri** [bucanero/apollo-ps4#11]
Hello I want to find a way to restore my saves from the original PS4 games or downloaded from the net, for the same game in PKG to recognize, tried for the same region, by ps4 mounter and apollo app, but without, games in question RDR2 and Witcher 3. can you help me ?

**Comment by bucanero** [comment]
Apollo can't currently mount or load encrypted ps4 save-games. (like the ones you export to USB using the XMB menu)

Some workarounds might be added in a future version, but right now Apollo can only read decrypted save-games. (like the exported by Apollo or Save mounter PC tool)

**Comment by bucanero** [comment]
This feature will be available in v1.0.0.

Encrypted saves need to be stored in a USB drive, in the standard PS4 path:
`/PS4/SAVEDATA/<account id>/<title id>/`

For example, Far Cry 4:
`/PS4/SAVEDATA/0123456789abcdef/CUSA14619/`

Files:
- `/PS4/SAVEDATA/0123456789abcdef/CUSA14619/FarCry4ProfileData`
- `/PS4/SAVEDATA/0123456789abcdef/CUSA14619/FarCry4ProfileData.bin`


Note: Apollo can't copy encrypted saves from newer firmwares. If the jailbroken PS4 has 5.05 firmware, the app won't be able to load an encrypted save from firmware 9.00 .

**Comment by ToniFabri** [comment]
My question is, I want to continue, I saved from an original game that was at 82% in a pkg game with the same id

I save from Apollo when my backup is in different files, since I had saved it before by usb, I wanted to convert the encrypted saves to apollo format, to be able to restore these saves of mine.

**Comment by SimonFoxcoon** [comment]
yeah this doesn't work for me. i was able view the account id of the save that i downloaded from the internet by replacing one of my saves in the save dir: /user/home/x/savedata/x
creating the folders and placing the encrypted save in the 
/PS4/SAVEDATA/<account id>/<title id>/   dir
and then going into the save tool, resigning the save from usb just results in corrupted save when i boot the game.

**Comment by ToniFabri** [comment]
> sim isso não funciona para mim. consegui visualizar o ID da conta do save que baixei da internet substituindo um dos meus saves no save dir: /user/home/x/savedata/x criando as pastas e colocando o save criptografado no /PS4/ SAVEDATA//<title id>/ dir e, em seguida, indo para a ferramenta de salvamento, renunciar ao salvamento do usb apenas resulta em salvamento corrompido quando inicializo o jogo. meu console não está ativado.

Yes my problema, save corrupted

**Comment by bucanero** [comment]
Retail games and fpkg games usually have different keystones. You can't use mix saves between those unless you swap the keystone files too.

PS4 save-games have many checks and IDs, you must resign and make everything match or else the save will be flagged as invalid.

**Comment by ToniFabri** [comment]
@bucanero There could be an alternative system for loading saves on the PS4 equal to the VMC on the PS2, where it would be possible to manage saves in a simplified way and just an image file, or create an option to convert in Apollo saves for the game to recognize
