### ISSUE TITLE
Load PS5 6.50 save on PS4 5.05

### ISSUE THREAD

**Issue by jul2003** [bucanero/apollo-ps4#112]
Hi,

On USB Saves menu when i do the copy save game to HDD apollo-ps4 does not ask if i want to sign the save or not . i get this error message Error! Can't mount encrypted save. (incompatible save-game firmware version) 
Doing that on my PS4 5.05 GoldHen 2.3 .
Save is from my 6.50 PS5.

Thanks

**Comment by jul2003** [comment]
I think it's the same as #104 and #110

**Comment by bucanero** [comment]
as explained in #104 , this is just not possible: the save on the PS5 has been encrypted with newer keys that are not available on 5.05 .

You might want to try on a ps4 with 9.00fw, but still if the ps5 keys are newer than 9.00, it will fail the same.
