### ISSUE TITLE
Apollo not viewing files on USB

### ISSUE THREAD

**Issue by MBeech1** [bucanero/apollo-ps4#121]
I start Apollo and go to USB saves but it only show the files on the external hard drive in the apollo directory, /mnt/usb0/PS4/APOLLO.

How can I get it to recognise the actual usb in the left usb slot.
The actual usb is formatted correctly and save to usb works fine from Apollo in the PS4/APOLLO directory

**Comment by bucanero** [comment]
Apollo auto-detects the first connected USB drive and uses it. If you want to use a different drive, just unplug any other drive and then Apollo will scan and detect the other one.

**Comment by MBeech1** [comment]
So the save games on the PS4 are saved on the internal and not on the external where all the games are then ?

**Comment by illusion0001** [comment]
Try #125

**Comment by bucanero** [comment]
Fixed in f27d5a3a7b9137d86090468733521011c52e2389

Added USB selection under "Settings" menu
