### ISSUE TITLE
Restore lastplayedgame from database

### ISSUE THREAD

**Issue by Nerago-Fikuxu** [bucanero/apollo-ps4#122]
Hey there, could you please add a feature to to fix the issue that after rebuilding the database the PS4 games do not go to the utmost left to be easily resumed or closed. Fixing this for me was setting the sortPriority column to 100 for all the games for all my users, then I replace the app.db on the ps4 and it works fine, I do not mess with the system apps, like Playstation Network or Internet Browser since I don't know what would happen messing with those.
On other note, could the fix the delete option of apps be applicable for all users executing just one time ? It is a bit tiring have to log into  each user and run the command on Apollo, but mostly asking to know if there is a reason for it to be just on the current user ?
Last questions I have are: If I make a backup of the ps4 database and restore it if the missing delete option occurs again, will it be unnecessary to run the fixes ? Does the backup of the db backs up the addcont db and any others that exist on PS4 ?

**Comment by bucanero** [comment]
you're probably trying to fix a database that was already restored with the old "python script" solution. That python script has many bugs and brings a lot of issues, like the "can't delete" problem.

I suggest you to:
- delete the current database (enter the PS4 boot menu and select the DB rebuild option)
- with a clean and empty database, install Apollo .pkg
- start Apollo, select the Database rebuild option. (no need to use any other option like "delete fix")
- restart your system, everything should show up. If some DLCs are missing, use the DLC rebuild option.

**Comment by Nerago-Fikuxu** [comment]
Hmm, that makes sense, will it also make the apps that I have set on a configured PS4 extended storage device show up normally or do I have to do the below steps ?:
- Go to Settings -> Devices -> USB Storage Devices
- Click the listed external storage -> Stop Using This Extended Storage
- Eject the external storage from the USB port
- Insert it back after a few seconds
After doing your suggested steps, would the safest thing to do be saving a backup of the app.db with Apollo and restoring it if I ever have to rebuild the database again ?

**Comment by bucanero** [comment]
Yes, for extended storage you need to follow those instructions.

> After doing your suggested steps, would the safest thing to do be saving a backup of the app.db with Apollo and restoring it if I ever have to rebuild the database again ?

Yes, if you use Apollo to keep database backups, then you can use Apollo to restore them and everything should be Ok. I suggest to make a backup after you install a new app or content, you can keep as many backups as needed.
