### ISSUE TITLE
cusa00411 save editor ?

### ISSUE THREAD

**Issue by Dbz9** [bucanero/apollo-ps4#138]
Hello, so everytime i try to export the decrypted file of my save and get the SGTA50000 file gta save editor give an error i did use the memory.dat file to decrypt the save but it's doesn't work sorry if my english is bad 
![image_2023-09-19_222753598](https://github.com/bucanero/apollo-ps4/assets/115960295/5d9cede9-bfac-4212-8aee-45395c78b4d5)

**Comment by bucanero** [comment]
you'll have to ask and check with the author of that Save editor, I don't know anything about it.

Maybe it's not meant for PS4, or needs something else as requirement.
