### ISSUE TITLE
Can't download spider-man save from online database

### ISSUE THREAD

**Issue by ClearableData** [bucanero/apollo-ps4#14]
when I'm trying to download it's always telling me "error downloading save game from apollo-db.psdev.tk/PS4/CUSA11993/00000004.zip

**Comment by bucanero** [comment]
Yes, there's an issue with the URL, it will be fixed in the next version.

**Comment by bucanero** [comment]
Fixed in a1594a8444f082d756b754d3072043ac90a03dc7
