### ISSUE TITLE
User ID and Trophies

### ISSUE THREAD

**Issue by IronJoy** [bucanero/apollo-ps4#147]
Hi,
My issue is weird, I needed to get some save file for FC24 done so, I download Apollo and installed it. Followed some instructions to offline activate user account ID-restart and then transfer from USB to HDD.
I've done all of that, but the issue is now I can't change my profile name nor access the trophies. The profile name is now in Italic font and every time I try to click on Profile or trophies, it asks me to go online "no internet access" screen.
More-over, the saves for the games, I've to apply them every time I want to play the game, the game itself doesn't save anything. At the beginning, "can't save personal data" errors and I've to start anew and even the same issue happened on a different user that I've never applied any save for, prior playing the game the same error. 

I'm only asking because now I'm worried about the trophies and saves in my HDD overall.

For this FC24 game, I clicked by mistake first on resign option, but that when I didn't see my saves on USB, but then I found them turns out I needed to create a folder called Apollo in PS4 folder in my USB. That was the only mistake I did, if it was.

Please, any help?

**Comment by bucanero** [comment]
You have activated a user account that was already in use. Saves and trophies will not work correctly in that case.

It has nothing to do with Apollo, it's a system issue. The recommended process is to only activate a newly created account, that has no saves or trophies. Then you can play and save without issues.

You can also delete your current account and start with a new blank one. Then activate it first, before doing anything else.
