### ISSUE TITLE
save location in documentation is wrong(?)

### ISSUE THREAD

**Issue by gut5** [bucanero/apollo-ps4#148]
The save location you have in your documentation appears to no longer work
What worked for me is:

`D:\PS4\APOLLO\1395b64f_CUSA11456_infamousssUser0`

The documentation says:

`USB saves | encrypted saves must be placed on /mnt/usbX/PS4/SAVEDATA/<account-id>/`

**Comment by bucanero** [comment]
no, documentation is correct, it has a note for **DECRYPTED** saves and another for **ENCRYPTED** saves


USB saves | your decrypted saves must be placed on `/mnt/usbX/PS4/APOLLO/`.
-- | --
USB saves | encrypted saves must be placed on `/mnt/usbX/PS4/SAVEDATA/<account-id>/`.

**Comment by gut5** [comment]
Did the path change from older versions? Because I don't remember Apollo saving things with that filename format.
