### ISSUE TITLE
Error about firmware version not matching only shows once and then doesn't repeat if you attempt to copy the save again

### ISSUE THREAD

**Issue by gut5** [bucanero/apollo-ps4#149]
I'm trying to copy a save to HDD, I get an error about firmware versions not matching, then when I press X and try to repeat the action it doesn't show the error the 2nd time, even if I remove the USB and exit the program and try the same actions again.

**Comment by bucanero** [comment]
If the firmware version is not supported, why would you want to repeat and retry? it won't work even if you retry 100 times.
