### ISSUE TITLE
Bloodborne is complaining about a save that isn't working 

### ISSUE THREAD

**Issue by gut5** [bucanero/apollo-ps4#150]
I'm trying to copy a Bloodborne (CUSA00207) save back which is in the location

`D:\PS4\SAVEDATA\6f1aa5d07727b9b4\CUSA00207`

and the filenames are SPRJ0005.bin (1kb) and sdimg_SPRJ0005 (36352kb), I'm choosing the "copy save to HDD" option (the save is on USB), apollo asks to "Re-sign save", I choose Yes, and then when I go into the game it's complaining about "Save Corrupted". I'm also getting similar results for some other games. And some games I was able to restore successfully. I can send you the save file if you like, let me know what method you prefer.

**Comment by bucanero** [comment]
Apollo expects encrypted saves exported by the PS4 XMB, and you're trying to import raw encrypted files. That won't work properly.

For example, a valid encrypted save exported by the XMB would be like:

```
/PS4/SAVEDATA/1234567890abcdef/CUSA01140/MGSVTPPSaveDataNA                          
/PS4/SAVEDATA/1234567890abcdef/CUSA01140/MGSVTPPSaveDataNA.bin
```

you might want to try renaming files, but I can't confirm the results.

**Comment by gut5** [comment]
I actually got those saves working using Apollo. If you like I can explain the steps, but I basically copied the encrypted save to the HDD (I get prompted to re-sign), I then exported the individual decrypted saves contained within the save on the HDD, then built a new profile/save on Bloodborne and imported the individual saves into that (so the profile in Bloodborne acts sort of like a container).

**Comment by bucanero** [comment]
thanks for the update, good to hear it worked.

Yes, having decrypted data files is always useful, as those can be "injected" back into other saves from a different account or user.
I always suggest to backup saves in decrypted format if you have a jailbroken PS4. (Encrypted saves should be only an option for users with non-hacked consoles)
