### ISSUE TITLE
Crash when using Chiaki for Windows

### ISSUE THREAD

**Issue by Bophades-Nauts** [bucanero/apollo-ps4#152]
I've noticed that using the app through Chiaki Windows client often causes Chiaki to crash, specifically when going to a save and clicking view details. Chiaki's Android app doesn't seem to have this issue. 

Not sure if this is something that can be fixed by you or has to be done by the Chiaki devs.

**Comment by bucanero** [comment]
This is not an issue with Apollo, it should be reported to the chiaki devs.
