### ISSUE TITLE
FW 11.00 update

### ISSUE THREAD

**Issue by koobzaar** [bucanero/apollo-ps4#154]
GoldHEN for 11.00 was released. Any plans for an update?

**Comment by dgrivera** [comment]
+Bump for this Ive tried it on the FW 11, the PS4 crashes :(

**Comment by Izofeu** [comment]
It works fine on 11.00, just says that save mount patch is needed.

**Comment by faroukbmiled** [comment]
> It works fine on 11.00, just says that save mount patch is needed.

how do you call that "works fine"

**Comment by faroukbmiled** [comment]
> It works fine on 11.00, just says that save mount patch is needed.

That means it doesn't work fine, we need updated shellcore patches

**Comment by Izofeu** [comment]
> > It works fine on 11.00, just says that save mount patch is needed.
> 
> That means it doesn't work, we need updated shellcore patches

It works better than what you described in your shamefully deleted reply where you clowned me for saying it works fine.

**Comment by kimochi777** [comment]
I am waiting for update on firmware 11.00 and also update for save file for granblue fantasy relink, I want to reassign it to another psn account, looking forward to it :)

**Comment by faroukbmiled** [comment]
> > > It works fine on 11.00, just says that save mount patch is needed.
> > 
> > 
> > That means it doesn't work, we need updated shellcore patches
> 
> It works better than what you described in your shamefully deleted reply where you clowned me for saying it works fine.

Its deleted for a reason (i thought it sounded rude), ur not about to argue on a GitHub issue lol,and im deleting this too the last thing devs want is this

**Comment by bucanero** [comment]
the only update required is finding the FW 11.x offsets for the save-game shellcore patches. Once someone takes the time to find the offsets, I'll rebuild Apollo.

**Comment by EadmondDai** [comment]
@bucanero 
I wonder, if I want to find the offsets, what tools do I need and where do I start.
I have some developing exp, but mainly in the games and software side.

**Comment by bucanero** [comment]
> @bucanero 
> 
> I wonder, if I want to find the offsets, what tools do I need and where do I start.
> 
> I have some developing exp, but mainly in the games and software side.

if you're wondering about FW 11 patches for save-game mounting, you need to check for example fw 9.00 patches for shellcore and savedata, and then find the new offsets on Fw 11.0 . For that you'll need kernel dumps to compare and trace where things could have moved.

9.0 savedata patches : https://github.com/bucanero/apollo-ps4/blob/27b3d621a36dacc17e41f45312aa9a133ab69d94/include/orbis_patches.h#L138

9.0 shellcore patches: https://github.com/bucanero/apollo-ps4/blob/27b3d621a36dacc17e41f45312aa9a133ab69d94/include/orbis_patches.h#L206

**Comment by AKuHAK** [comment]
Offline Account activation doesnt work, all accounts has lock symbol and didnt popup the window with new id. Tested with 1.4.2 and [apollo-ps4-build_27b3d621](https://github.com/bucanero/apollo-ps4/actions/runs/9121049059/artifacts/1511527390). Also in the option "Show parental control" app is crashing.

**Comment by Eni0** [comment]
@Account activation work.

**Comment by AKuHAK** [comment]
> Account activation work.

![Screenshot 2024-05-19 at 21 38 47](https://github.com/bucanero/apollo-ps4/assets/621640/b491b1c7-a7a0-459c-b681-cf7ce7dee7e4)
Pressing X has no effect

**Comment by bucanero** [comment]
Create a new blank account, and test again. The screenshot is incomplete and provides no useful information. Enable debug logs from Settings and try with a new blank account.

**Comment by Daasin** [comment]
Could it also be made to work on 10.00/10.01? 

Will test with a new account now 🫡

**Comment by Daasin** [comment]
> Could it also be made to work on 10.00/10.01? 
> 
> Will test with a new account now 🫡

It said its successful and a reboot might be required with a bookmark symbol instead of lock. I didn't even need to make a new account.

**Comment by Daasin** [comment]
ERROR 809F0006 can't mount xxx
Cannot open database file trophy_local.db
Dumping all fingerprints from saved ta.db

**Comment by Daasin** [comment]
ERROR 809F0006 can't mount xxx
Cannot open database file trophy_local.db
Dumping all fingerprints from saved ta.db 

How is that? @bucanero i tried to type out all parts I thought were relevant

**Comment by bucanero** [comment]
> Hi @bucanero can you update apollo for ps4 firmware 11 

A few developers are already working on this, but not a high priority. 

Posting the same request a million times won't make any difference. You can either find offsets and do research yourself, or support developers (through donations).

**Comment by bucanero** [comment]
If some users on FW 11 want to test, there's a developer build thanks to Lightning mods and Socratic bliss   

Check #156

**Comment by Daasin** [comment]
im on 10, could anything be done for that? I mean ill try this one on it but its probably not going to work, right?

**Comment by bucanero** [comment]
> im on 10, could anything be done for that? I mean ill try this one on it but its probably not going to work, right?

No, it won't work on 10.x

**Comment by Noxde** [comment]
> If some users on FW 11 want to test, there's a developer build thanks to @LightningMods and @SocraticBliss
> 
> Check #156 , dev build: https://github.com/bucanero/apollo-ps4/actions/runs/9164427117/artifacts/1520513404

Working on FW 11.00. just resigned a save and i can hex edit it and copy it to hdd

**Comment by bucanero** [comment]
> > If some users on FW 11 want to test, there's a developer build thanks to @LightningMods and @SocraticBliss
> 
> > 
> 
> > Check #156 , dev build: https://github.com/bucanero/apollo-ps4/actions/runs/9164427117/artifacts/1520513404
> 
> 
> 
> Working on FW 11.00. just resigned a save and i can hex edit it and copy it to hdd, let me know if i should test something specific

If mounting and editing works fine, then the only thing left to check would be importing an encrypted save from USB. 

If you can check the encrypted import, please report results to confirm everything is working

**Comment by Noxde** [comment]
> > > If some users on FW 11 want to test, there's a developer build thanks to @LightningMods and @SocraticBliss
> > 
> > 
> > > 
> > 
> > 
> > > Check #156 , dev build: https://github.com/bucanero/apollo-ps4/actions/runs/9164427117/artifacts/1520513404
> > 
> > 
> > Working on FW 11.00. just resigned a save and i can hex edit it and copy it to hdd, let me know if i should test something specific
> 
> If mounting and editing works fine, then the only thing left to check would be importing an encrypted save from USB.
> 
> If you can check the encrypted import, please report results to confirm everything is working

Just got an encrypted save on my usb and copied it to the hdd, the save is resigned and working fine

**Comment by OddOttAllen** [comment]
will test pretty soon! pretty excited about this :)

**Comment by BleedingXiko** [comment]
> If some users on FW 11 want to test, there's a developer build thanks to @Lightningmods and @Socraticbliss   
> 
> 
> 
> Check #156 , dev build: https://github.com/bucanero/apollo-ps4/actions/runs/9164427117/artifacts/1520513404

Getting a 404 with that link

**Comment by faroukbmiled** [comment]
I have forked and built the project (using bucanero's build action) and released a test build for anyone that cant access the [artifact](https://github.com/bucanero/apollo-ps4/actions/runs/9164427117/artifacts/1520513404)

[here](https://github.com/faroukbmiled/apollo-ps4/releases/tag/Test)

**Comment by Daasin** [comment]
Crud, should I make a new issue for 10.00/01?

**Comment by bucanero** [comment]
> Crud, should I make a new issue for 10.00/01?

Yes, anything not related to FW 11.0, open a new issue.

**Comment by ereh19** [comment]
> Great to hear. I'll wait for some additional feedback from other FW 11 users. If nothing else shows up, I'll build a new release.

everything working fine, tested by me
