### ISSUE TITLE
10.00/10.01 Support?

### ISSUE THREAD

**Issue by Daasin** [bucanero/apollo-ps4#157]
Save patches and trophies dont seem to work but activating offline account does, is it possible for us to get support like the 11.00 people did?

**Comment by Daasin** [comment]
Thanks in advance for any response

**Comment by bucanero** [comment]
FW 10.x will require new specific patches to handle save games.

As mentioned in #154 , I'm working on other projects so other devs/users will have to find offsets for this new firmware before any 10.x support can be added.

**Comment by Assassin9520** [comment]
Hi, anyone with enough kernel(asm) offset dumping experience?
 I am willing to take some time to look into this issue, but not enough xp on my own now.

**Comment by bucanero** [comment]
> I can probably do the 10.0 but, maybe there is some other problems.
> 
> I tried to port it to 10.50 ([BestPig@329df45](https://github.com/BestPig/apollo-ps4/commit/329df45e405393905797da9f0facada580382e8a)) But the pkg (my build) or the official one make the console into Kernel Panic when launching the app. The application normally detect if a firmware is incompatible so it shouldn't make it crashes or I missed something.
> 
> Can you check if the pkg is making your 10.0 console into crash? If not, I can look to port offsets for 10.0.

the 10.50 patches in that commit seems to have the exact same offsets as the 11.00 patches, is that correct?

regarding the kernel panic, it could be that offsets are wrong, or that the HEN used on 10.50 doesn't have the required syscalls. The current memory patching requires either GoldHEN, or ps4debug payload to be available.
So if you're using something like regular ps4-hen, I think you could get a crash because of that too.

Also, no idea how you're building the app,  maybe your OpenOrbis setup or toolchain is not right. I suggest trying to build an unmodified version using GitHub actions, and test if that .pkg works. Then you can test additional changes.

**Comment by BestPig** [comment]
Yes I was also surprise that some offset are totally similar, but they should be right.

I didn't knew GoldHEN or ps4debug was present, its probably the cause, I'm using the regular HEN yes.
But as I saw you are checking fw version and that goldhen or ps4debug is present, so it should not crash the console :/.

I did the build using your github actions, so should not be the problem.
And it's crashing also with your pkg, so maybe checks of installed syscall is making it crashes, will do some tests.
Thanks for your answer.

**Comment by bucanero** [comment]
The goldhen/ps4debug check is not something bullet-proof so it could fail/crash if the HEN implementation is unexpected.

I suggest to test with the latest v1.4.4 release .pkg, if the latest release crashes with KP, then most probably the goldhen/ps4debug check could be the root issue.
If the latest release doesn't crash, and shows "unsupported firmware version" and patches are not applied, then it might be related to your .pkg build.

Also, if you get get the 10.00 patch offsets it could be tested with 10.00 Goldhen, as I think currently there's no 10.50 goldhen payload.

**Comment by BestPig** [comment]
I was testing with the 1.4.4 and it crashes on my 10.50 hen, so probably the check.

I did the offsets port to 10.00 if someone with GoldHen wants to check if it works, the build is [here](https://github.com/BestPig/apollo-ps4/actions/runs/9473680283/artifacts/1591596129)

**Comment by Assassin9520** [comment]
Does it work also on 10.01? I can check it following days.
Is it possible to show me how you did it?

**Comment by bucanero** [comment]
No, currently this build by @BestPig doesn't work. Most probably the offset patches are not right, or some additional patches are required. 
You're free to test but feedback said it didn't work.

**Comment by BestPig** [comment]
This version should now works also on 10.01 if you want to try.
https://shareit.bestpig.fr/get/6a18257d529e8efe8d01855adcdef9b7a37748eb/apollo-ps4-build_972024af.pkg

**Comment by Assassin9520** [comment]
I will also check it and feedback.

**Comment by Assassin9520** [comment]
(very) late edit: works as expected
