### ISSUE TITLE
Debug log option on/off

### ISSUE THREAD

**Issue by Invictaz** [bucanero/apollo-ps4#163]
I had a crash but did not enable debug log before.
Is it possible to make debug and or crashlogs automatically on instead of manually single use?

**Comment by bucanero** [comment]
I guess the "debug log" could become an option in the settings menu, with the `on/off` setting (like music or animations)

it would be `off` by default, but if the user enables it, the debug logging will remain enabled every time the app starts.

**Comment by Invictaz** [comment]
Would be double for me

**Comment by bucanero** [comment]
No, system crashes will not be logged, it's only application information. For system log you should use the gold hen payload options.

**Comment by Invictaz** [comment]
Uhm I'm not sure since there is no payload to be found to log 11.0 system shutdowns? From what I have read it's due to Apollo reading or writing to memory what can cause leaks or memory problems which might turn off the system?

**Comment by bucanero** [comment]
As stated, Goldhen has TTY logs settings, you'll have to search and learn on how to enable and use it. Those are low kernel level logs that will track everything.

I won't repeat this again:

**Support for 11.0 firmware is experimental, the save-mount patches (shared by LMods) might still require adjustments/fixes for new security measures. I'm on 6.72, so I'm not spending time on it.**
