### ISSUE TITLE
Please, add cloud save support to Gmail, OneDrive...

### ISSUE THREAD

**Issue by FaLL3N-ighT** [bucanero/apollo-ps4#165]
Please add cloud save support man for our normal save, to Gmail, OneDrive, etc...i am desperately looking for this option..thank you !

**Comment by bucanero** [comment]
if I ever add a feature like that, it won't support any vendor-specific API like gdrive, onedrive, dropbox, etc.

I'd probably add support for a standard protocol like FTP, and each user can use their own local or hosted ftp server.

**Comment by FaLL3N-ighT** [comment]
Thanks for your reply first....i don't want to offend, but why can't it be ?..on ps3 cfw has this kind of option!

**Comment by bucanero** [comment]
I don't want to. If someone else wants to do it, they can build such things.

**Comment by FaLL3N-ighT** [comment]
lol man...ok ( i guess ) thats strange...I was thinking that an option similar to those from Sony ( and not only ) would be welcome...but if that's it, that's it..
