### ISSUE TITLE
Required firmware ：8.00+

### ISSUE THREAD

**Issue by 1290504000** [bucanero/apollo-ps4#166]
HELLO！
When I was using APOLLO, I found that importing the  saves would prompt me to upgrade the system. My PS4 is version 7.62. Can this be resolved，thanks！

**Comment by bucanero** [comment]
No, you can't import encrypted saves from higher firmwares. It's not possible, the system doesn't have the keys.

**Comment by 1290504000** [comment]
OK... Can I import encrypted saves if I upgrade the ps4 to the 9.0 system
