### ISSUE TITLE
9.60 support?

### ISSUE THREAD

**Issue by unxw** [bucanero/apollo-ps4#169]
just wondering if there is / will be support for 9.60? thank you!
also, if not, should i update to 11?

**Comment by bucanero** [comment]
FW 9.60 will require new specific patches to handle save games. (Maybe similar to 9.00 patches, but most probably some stuff needs to be adjusted.)

As mentioned in https://github.com/bucanero/apollo-ps4/issues/154 , I'm busy working on different projects so other developers will have to find offsets for this new firmware before support can be added.

I wouldn't update the system, but anyways it's a personal choice.

**Comment by BestPig** [comment]
This version should work on 9.60 if you are running GoldHEN and not vtx-hen
https://shareit.bestpig.fr/get/6a18257d529e8efe8d01855adcdef9b7a37748eb/apollo-ps4-build_972024af.pkg
