### ISSUE TITLE
Support for 9.03

### ISSUE THREAD

**Issue by seathasky** [bucanero/apollo-ps4#178]
Using EchoStretch's ps4-hen-vtx on 9.03. Any chance Apollo will ever get support for this firmware? Thanks!

**Comment by bucanero** [comment]
There's a test build that should support 9.03 . You can test and report results (you'll need latest PS4HEN 2.1.5)
https://www.mediafire.com/file/3sryqx4ppmophor/apollo-ps4-build_143f5720.zip/file

See #177

**Comment by seathasky** [comment]
Thank you for pointing this out! Appreciate it
