### ISSUE TITLE
Hello, best app, up saves RDR2 , Wicher3 and GTsport, thanks

### ISSUE THREAD

**Issue by ToniFabri** [bucanero/apollo-ps4#18]
is there any site where i can download decrypted saves?

**Comment by bucanero** [comment]
> is there any site where i can download decrypted saves?

Most sites I know have encrypted saves, but if any user has a useful save and can run Apollo, they can export it as `.Zip` and share the decrypted save easily.

If users want to share, I can upload those saves to the "Online DB" so they're available directly from Apollo's menu.
