### ISSUE TITLE
[Request] Please add documentation on `owners.xml`

### ISSUE THREAD

**Issue by Whovian9369** [bucanero/apollo-ps4#180]
Hello!

I am requesting documentation on `owners.xml`. For example...
- When to use it.
- How one would use it to properly activate their local account.
  - Like for copying save data between PS4 and PS5 for example.
- How to get the specific values for PS3 or PS4, appropriately.
  - Needed to use the `console.idps` or `console.account_id` sections for PS4 use.
- etc etc.

Thank you for the time!

**Comment by bucanero** [comment]
the data in `owners.xml` is for reference only, there's nothing special about it. `console` data is unique IDs from the console, `user` is data from the user account.

If you want to activate an account, you can use the `account_id` you want, as explained here: https://github.com/bucanero/apollo-ps4#offline-account-activation

As long as you use the same `account_id` , saves will be owned by the same user across systems.
