### ISSUE TITLE
PS4 Pro 3840x2160 support ?

### ISSUE THREAD

**Issue by Neucher** [bucanero/apollo-ps4#20]
I know this isn't that important but I don't know any other homebrew app that has native PS4 Pro support. Is it even possible ?

**Comment by bucanero** [comment]
I'm not aware of any homebrew app currently working on 4K resolution. 
In theory it could be done, but I'm not sure if Open Orbis has any example or code that can handle 4k right now.

**Comment by Lehner82** [comment]
Would it be possible to make the UI render at 2160p ? I would be more than happy to test that. It would certainly be interesting if it's a simple code change or if it requires more optimizations.
