### ISSUE TITLE
Suggestion: decouple patches from releases

### ISSUE THREAD

**Issue by subworx** [bucanero/apollo-ps4#25]
Hi again,

I have another suggestion: allow updating the save patches independently from the application.
Means whenever you create a new app build, all current cheats are included. 
But if something is added later, the tool can check online (on request and/or startup) and download and instantly use new or updated patches instead of waiting until you actually build a new release.

Thank you :)

Update: I found I can do this manually (or test patches \o/ ) by dropping stuff to `/data/apollo/data/`, yay :)
What does the button "Update Application Data" in settings do? Tried removing CUSA17419.savepatch over FTP, then update data with that option, and nothing happened in the data directory.

**Comment by bucanero** [comment]
This is already supported, that's the reason for the "update application data" option.
As you said, you can just place whatever patch file you want directly on `/data/apollo/data/` and Apollo will use the new patch file.

If your PS4 is connected to the network and you select "update application data", if everything works as expected, Apollo will download the latest "patch pack" from the GitHub server (https://bucanero.github.io/apollo-saves/PS4/ps4appdata.zip) and unzip the contents to /data/apollo/data

The idea behind it is to be able to release new patches even if there's no new Apollo version.
