### ISSUE TITLE
Application crashes when trying to view trophies

### ISSUE THREAD

**Issue by TheRozitaKnight** [bucanero/apollo-ps4#28]
The app crashes when trying to view trophies on 9.00. I tested it on a non-activated account with saves and trophies.

**Comment by bucanero** [comment]
do you get a list of trophies, or the app crashes before listing any title?

**Comment by TheRozitaKnight** [comment]
It crashes before listing anything. I see a brief "Loading save games..." message before the crash.

**Comment by subworx** [comment]
Unfortunately the debug log is not very informative.

```
[2022-02-03 17:10:45] ----- File (/data/apollo/apollo.log) debug logger initialized -----
[2022-02-03 17:10:47] Saving Settings...
[2022-02-03 17:10:51] Opening 'file:memdb?ptr=0x200E60020&sz=1605632&freeonclose=1'...
[2022-02-03 17:10:51] [NPWR09746_00] F(640) name 'Trackmania Turbo'
(snip)
[2022-02-03 17:10:51] [NPWR16884_00] F(640) name 'The Pathless'
```
This is everything, I just snipped out a list of >100 entries with the same schema (datetime, nprwID F(640) name 'somegame').

**Comment by bucanero** [comment]
> Unfortunately the debug log is not very informative.

are you also getting a crash when listing trophies? could you send the `trophy_local.db` file? I never had such crash so I think it might be related to the content of the trophy file.

**Comment by subworx** [comment]
A one download only link, hope you are the first to click it ;)
https://file.io/uXID0rlPX77i

**Comment by TheRozitaKnight** [comment]
I deleted some trophies and my trophy_local.db. The system recreates the database after you logout and login again, so you don't lose your trophies (except those you deleted from the filesystem).

[Here's my current trophy_local.db.](https://file.io/hTPnmzgHMXgy)

**Comment by bucanero** [comment]
I've got the trophy.db files 👍  and I'll check them when I have a chance, but it might take a while as I'm currently working in some other ps4 project along with SiSTRo

**Comment by subworx** [comment]
No worries, take your time.
Looking forward what will come out of this collaboration :)

**Comment by bucanero** [comment]
as noted by @arfgh on #36 , the bug comes from empty entries on the trophy_local database. (where `status=1`)
