### ISSUE TITLE
Earned trophies backup/restore

### ISSUE THREAD

**Issue by andreltrigo** [bucanero/apollo-ps4#29]
A way to decrypt and backup/restore earned trophies would be nice, especially for transferring between accounts. Is it possible to implement such a feature?

**Comment by bucanero** [comment]
I could add trophy-related features just as Apollo has on PS3, but I haven't seen anyone sharing any information or tool to export/mount trophies at all. I don't have time for deep research, so if anyone is willing to provide the info, then a proper feasibility-check could be done.

**Comment by TheRozitaKnight** [comment]
The only info I could find is [this page](https://www.psdevwiki.com/ps4/Trophy). I don't have the know-how to do a deep research, so it'd be great if someone else could contribute.

**Comment by CygnusHyoga** [comment]
Here is more info/examples:

[https://www.psxhax.com/threads/ps4-sealedkey-pfsskkey-for-savegame-trophy-data-decryption.2185/](url)

[https://github.com/xXxTheDarkprogramerxXx/PS4_Tools/tree/master/TrophyUnlocker](url)

**Comment by subworx** [comment]
As a workaround for backup/restore, copy via FTP:
`/user/home/<yourID>/trophy/*`
`/user/trophy/*`

As for the code, in the OpenOrbis toolchain samples, there is another trophy unlocker:
https://github.com/OpenOrbis/OpenOrbis-PS4-Toolchain/tree/master/samples/trophies

**Comment by TheRozitaKnight** [comment]
Yeah, but it's still encrypted, so you can't import it into another account.

**Comment by leolapi4** [comment]
> 

You can obtain the decrypted one during the game is running.

**Comment by TheRozitaKnight** [comment]
Where is the decrypted file located? I've tried looking around /mnt via FTP while a game is open, but couldn't find anything.
