### ISSUE TITLE
Crashes on PS4 9.00 - GoldHEN 2

### ISSUE THREAD

**Issue by caotain3278** [bucanero/apollo-ps4#3]
Looked forward to your tool...

V5.00 worked very slow for me., so i didn't test it further. 

v6.00 crashed my system twice after the looding screen, so i had to stop testing.

**Comment by bucanero** [comment]
firmware version? using GoldHEN 1, Goldhen 2? other payloads running?
Maybe the automatic save-mount patches are failing, but more details are needed.

**Comment by caotain3278** [comment]
I'm running 9.00 with Golhen 2. 
No other payload running

**Comment by bucanero** [comment]
Just to rule out if it's related to 9.00 save-mounting patches or not, here's a version without any 9.00 patches: https://www.mediafire.com/file/0vfll17c37i1oer/IV0000-APOL00004_00-060_no900patch.pkg/file 

Without patches Apollo won't be able to open the save-data on HDD, but the app should boot without crashes.

**Comment by caotain3278** [comment]
This Version boots fine. I get an unsupported FW 9.00 Message bit it loads. 

As u said: not able to open save-data on hdd

Stupid question: is a network connection required for your tool? Mine is diasbled...

**Comment by bucanero** [comment]
> This Version boots fine. I get an unsupported FW 9.00 Message but it loads.

Alright, thanks for the feedback. Then the 9.00 save-mount patches are crashing the system.

I made another build in case you want to test, with the exact same 9.00 patches from the Save-Mounter app by [AGrabber](https://github.com/AGraber/Playstation-4-Save-Mounter):
https://www.mediafire.com/file/wc3bjzvzsalix3e/IV0000-APOL00004_00-new900patch.pkg/file

If this build works without crashing, then a few additional 9.00 patches were wrong, and I just took them as valid. If you test, let me know if you can access save-games from HDD too.

> 
> Stupid question: is a network connection required for your tool? Mine is diasbled...

if available, network connection can be used for the "Online DB" , and for the new version check. The version check can also be disabled from the Settings menu. But if the network is disabled the app will work too.

**Comment by caotain3278** [comment]
I‘ll test it later and will let u know

**Comment by cescx3** [comment]
tested and unfortunately keeps crushing.

> https://www.mediafire.com/file/wc3bjzvzsalix3e/IV0000-APOL00004_00-new900patch.pkg/file

**Comment by bucanero** [comment]
Alright, thanks for the feedback, so even with the minimum patches it fails. 🤔  maybe it's something with the GoldHEN 2 syscalls. I'll talk with Sistro to check about goldhen on 9.00.

**Comment by bucanero** [comment]
From feedback and logs, it seems that the ShellCore patches on 9.00 are breaking something with `sceSaveDataMount2`, then the app crashes when trying to load settings.

Unfortunately I'm on 6.72 so fixing this will take some time. I have removed 9.00 from the supported list, and replaced the release with the "no-patch" version. So any new user with 9.00 will just get the `Unsupported firmware v9.00` message but will avoid crashes.

**Comment by bucanero** [comment]
Thanks to @ac2pic, the broken `ShellCore` patch on fw 9.00 has been identified. The correct offset has been updated (8b4b6f11c4e89a643aae427e6f75ed456f4497df)

The fix should be available in the next release.

**Comment by bucanero** [comment]
Fixed in [0.7.0](https://github.com/bucanero/apollo-ps4/releases/tag/v0.7.0)
