### ISSUE TITLE
Decrypted Save File Conflict

### ISSUE THREAD

**Issue by CrypticEntity** [bucanero/apollo-ps4#32]
Some games have identically named decrypted save files. This causes Apollo to refuse to open savedata where you have already extracted the savedata of a different encrypted save with the same decrypted name and title ID. It's kind of hard to word but I think that explains the problem well enough.

**Comment by bucanero** [comment]
I don't really understand what's the issue you're trying to mention.

Please, write down a step-by-step example of what you are doing and what results you see. Write down all the details, save-game, title id, folder, or else I won't be able to reproduce the issue.

**Comment by CrypticEntity** [comment]
Game: Persona 5 royal (cusa17419)
having 2 ingame saves creates 2 data entries
Encrypted they are called "DATA0" and "DATA1"
Both are unencrypted named DATA.dat
If you unencrypt DATA0, it extracts to /data/apollo/userID/titleID/data.dat
Then if you then open DATA1 it fails to open with a generic error due to an incorrect data.dat file stored where DATA0 extracted itself to.

**Comment by bucanero** [comment]
if `DATA0` is actually a file inside a save-game, then it should be extracted as DATA0, not "DATA.dat". 

are you opening a save on your HDD? if you select the option to extract single decrypted files, you should get a list of available files to decrypt. The extracted file will keep the exact same file name.

Still, some missing details are not clear, if it's a HDD save? USB save? encrypted USB?

**Comment by subworx** [comment]
Many games do that, the decrypted save name is the same for all (differently named) slots.
Persona 5 Royal saves are named `data.dat` after extraction but `data01.bin, data02.bin` in the file system.
All Unreal engine games have `ue4savegame.ps4.sav` no matter the slot number. 
Example: Solar Ash slot 1 is called `File 1` on the PS4, `/home/user/UserID/savedata/CUSA26035/Save0.bin` in the file system, slot 2 would be `Save1.bin`. 
Still, both contain the file with the same name `ue4savegame.ps4.sav` so if I extract `File 1`, then `File 2`, the contents of `/data/apollo/UserID/CUSA26035/` would be one `ue4savegame.ps4.sav` from slot 2.

Not sure how to best prevent/circumvent this.

**Comment by bucanero** [comment]
I'm addressing this issue by using a specific folder for each save-game (not just TITLE-ID). The folder will be `TITLEID_DIRNAME`. For example:

- `/data/apollo/userID/CUSA17419_DATA01/`
- `/data/apollo/userID/CUSA17419_DATA02/`

That way, even if the slots have the same file names inside, they'll be extracted to different folders, like:
- `/data/apollo/userID/CUSA17419_DATA01/savegame.sav`
- `/data/apollo/userID/CUSA17419_DATA02/savegame.sav`
