### ISSUE TITLE
Horizon Zero Dawn mis-recognized

### ISSUE THREAD

**Issue by subworx** [bucanero/apollo-ps4#35]
Hi,
More of a cosmetic issue:
I have installed `CUSA10212` (Horizon Zero Dawn Complete Edition - EU/ES), but Apollo recognizes it as `CUSA07319` (Horizon Zero Dawn - EU/ES) instead.
Pkg info says CUSA10212, Entitlement Manager says CUSA10212, but Apollo claims it were CUSA07319 and also creates the directory with that name on export.
Imported a save to test it, and it worked as expected, still confusing though.

**Comment by subworx** [comment]
Hm 
`/system_data/priv/appmeta/CUSA10212/param.sfo` says "INSTALL_DIR_SAVEDATA" - "Titlle ID used by Shared Save Data" - "CUSA07319".
Nowhere else in the .sfo is CUSA07319 mentioned, according to orbis-pub-sfo. Could this be a parsing error with Apollo?

Dragon Quest XI Definitive (CUSA19120) has the same setup (Shared Save Data -> CUSA19290) but does not show the same behaviour, Apollo lists the correct Title ID.

**Comment by bucanero** [comment]
Title ID is taken from the SQLite savedata database. I'd check the database file, I'm pretty sure the DB will have `CUSA07319` there.
