### ISSUE TITLE
CE-3116-4 Error

### ISSUE THREAD

**Issue by MindlessToxin423** [bucanero/apollo-ps4#39]
I've been having the hardest time trying to transfer saves for Horizon Zero Dawn Complete Edition from one account to the other(same ps4). I offline activated new user account. Even signed saves on the USB before copying to HDD.  It keeps giving me a ce-3116-4 error or corrupt save.

**Comment by MindlessToxin423** [comment]
i ended up using ChendoChap's Save Mounter. It was a longer process but worked fine.

**Comment by bucanero** [comment]
Anything done with Save Mounter can be done with Apollo.

The best way to avoid issues is to create a new game save under the destination account, and then just replace the decrypted data file:

- open source save and extract the decrypted data file
- switch to the new console/account/etc and create a new save-game
- open the new save-game, inject the decrypted data file from step 1

Some games have additional security checks so this is the best way to skip all the issues.

**Comment by bucanero** [comment]
> I've been having the hardest time trying to transfer saves for Horizon Zero Dawn Complete Edition from one account to the other(same ps4). I offline activated new user account. Even signed saves on the USB before copying to HDD. It keeps giving me a ce-3116-4 error or corrupt save.

for reference, this might be related to #98 , if HZD saves are using `SAVEDATA_LIST_PARAM` on param.sfo

**Comment by bucanero** [comment]
You can test out this `pkg` build and see if it works with thoze HZD saves:
https://github.com/bucanero/apollo-ps4/suites/10157426095/artifacts/496372357
