### ISSUE TITLE
Unable to load/save in games after launching Apollo

### ISSUE THREAD

**Issue by 2C55FEA7CC** [bucanero/apollo-ps4#43]
I have been experienced a repeating problem whenever i use this tool:
I can't save and load in games and most games also give me a CE-33116-4 error ("most" because one game just refuses to load/save without error)
This isn't a issue with the save files since it only happens after starting apollo without having done anything to the save files.
I also tried to use my the disks instead of my dumps but that results in the same issue.
And to fix this issue i have to restart the console which is a pain to do every time after using this software.

**Comment by bucanero** [comment]
I guess you're closing the app with the PS button, so the save-mount patches remain in memory affecting other apps.

You need to exit Apollo using the `circle` button on the Main Menu, a message window will ask "exit to XMB?", click "yes", and wait for the app to return to the XMB. Finally, a notification pop-up will say that the save-mount patches were removed from memory.
