### ISSUE TITLE
Question about the bytes endianness of Save Wizard format savepatch

### ISSUE THREAD

**Issue by sagan** [bucanero/apollo-ps4#45]
Hi, I am trying to write a savepatch for Persona 5 Royal Japanese version (CUSA08644) for my own purpose and I have a question about the byte endianness.

According to [this document](https://playersquared.com/forums/81-save-wizard-quick-codes/3012-save-wizard-custom-quick-code-formats.html), The majority of PS4 saves use Little Endian but Save Wizard uses Big Endian. Save Wizard will automatically swap the Endian for those specific (Big-Endian) games. Therefore, "000F423F" in a code will write as "3F420F00" in the save for most (Little-endian) games.

I have found that the Persona 5 Royal (JP) savedata use big-endian. For example, write the "00 98 6F 70" four bytes at offset 0x00355C of save data file "data.dat" will set money to 9,990,000 (986F70). When writing a savepatch for Apollo it would look likes:

CUSA08644.savepatch

```
;CUSA08644
;PS4 Persona 5 Royal (JP)

:DATA.DAT

[max money]
2000355C　00986F70
```

Will it work or I need to change the modification value to the opposite endianness "706F9800" ?

**Comment by bucanero** [comment]
Apollo's implementation of Save wizard on PS4 handles all the write codes (like code types `1`, `2`) as little-endian, so when written they'll be swapped.

The original save wizard might have an internal database that tracks if any specific game is "big endian" and then skips the swap, but I don't have such information so all games are handled as little-endian.

So, if you want to write a 4-byte value `11 22 33 44` using code type 2, you'll have to write the code:

```
2000ABC0 44332211
```

another option is to write everything with single bytes, but will make codes larger:

```
0000ABC0 00000011
0000ABC1 00000022
0000ABC2 00000033
0000ABC3 00000044
```

anyways, just remember that Apollo on PS4 will handle write codes as little-endian. (Apollo on PS3 will write as big-endian)

Btw, if you test the code and works, please share the `CUSA08644.savepatch` file and I'll add it to the next release.
