### ISSUE TITLE
Add compatability for 5.07

### ISSUE THREAD

**Issue by noob111111** [bucanero/apollo-ps4#48]
I think its the same as 5.05 so it should work the same as 5.05

**Comment by noob111111** [comment]
By the way as my name suggests i am a complete noob in the ps4 homebrew action scene

**Comment by bucanero** [comment]
Are you using a 5.07 firmware console? Do you use gold hen? Please provide more details

**Comment by noob111111** [comment]
ok i will provide as much information as i can, and you can later ask for more information. i AM using a 5.07 firmare console, i use goldhen v2.2.2 i have tried the current version of apollo save tool and it said 5.07 unsupported firmware

**Comment by bucanero** [comment]
> ok i will provide as much information as i can, and you can later ask for more information. i AM using a 5.07 firmare console, i use goldhen v2.2.2 i have tried the current version of apollo save tool and it said 5.07 unsupported firmware

Download and try the .pkg in this zip file:
https://www.mediafire.com/file/zuyb2kzusjg1ura/apollo-ps4-build_8024527d.zip/file

Firmware 5.07 should be detected now. Please reply with feedback to confirm if it works or not.
If you can copy and access your saves correctly, then I'll add this change to the next Apollo release.

**Comment by noob111111** [comment]
it works!!! i have only tried it in one game but as far as i can tell it works great!
