### ISSUE TITLE
Save listing requests

### ISSUE THREAD

**Issue by subworx** [bucanero/apollo-ps4#5]
Hi, great work on the editor so far.
Already looking into how to add more savegame cheats :)

Please add save sorting by various criteria: Game Name (if possible), CUSA or Save Name.
Grouping Saves by Game would be great.
Can the control hints at the bottom please stay on screen instead of vanish after a second, especially since nothing else happens down there?

**Comment by bucanero** [comment]
> Please add save sorting by various criteria: Game Name (if possible), CUSA or Save Name. Grouping Saves by Game would be great. Can the control hints at the bottom please stay on screen instead of vanish after a second, especially since nothing else happens down there?

I'll keep these in mind for future updates.

> Hi, great work on the editor so far. Already looking into how to add more savegame cheats :)
> 

If you want to help and add more cheats, here's an example on how to write down the save-wizard codes:
https://github.com/bucanero/apollo-ps4/blob/main/appdata/CUSA00004.savepatch

The cheat file must be named TITLEID.savepatch , so for example `CUSA12345.savepatch`
If you look at the link, the first few lines that start with `;` are comments

```
;CUSA00004 
;PS4 Infamous Second Son 
;source: hackinformer forum 
```
then, the next line that start with `:` is where you can define which file to patch. `*` (asterisk) means any file. If you know the specific file, you could put for example `:PROFILE.BIN`. In most cases we don't have info and leave `:*` so the user selects the file while using Apollo.

```
:*
```
next comes the Save Wizard codes, in a simple format:

```
[cheat code name]
01234567 0ABCDEF7
01234567 0ABCDEF8
...etc...

[another cheat]
01234567 0ABCDEF8
01234567 00CCEEFF
```

there are some websites that have PS4 save wizard codes. We just need help from the community to collect them and add those files to the app. For example these sites:
- https://forum.hackinformer.com/viewforum.php?f=115
- https://xdgmods.com/category/save-wizard-quick-codes/

the more codes we can add, the better... of course, some might not work and are untested, but it's easier to add everything first and then just filter when someone reports that something is not working.

**Comment by Pharaoh2k** [comment]
Thanks for the amazing tool! Awesome work!
I second the request for being able to sort at least by CUSA.
It is quite a pain to search the list when there are many games and saves and they are all sorted by title name only, as there are many games that have a different save name, but the CUSA is the same.
Thanks again! :)

**Comment by bucanero** [comment]
Save sorting options added in https://github.com/bucanero/apollo-ps4/commit/c416555a698b355b02140ea00f3a60b049261940
