### ISSUE TITLE
Apollo savepatch

### ISSUE THREAD

**Issue by OfficialAhmed** [bucanero/apollo-ps4#54]
First test More saves on the way
[apollo saves.zip](https://github.com/bucanero/apollo-ps4/files/8525777/apollo.saves.zip)

**Comment by OfficialAhmed** [comment]
here are 11 more quick codes
[pack 2 savepatch.zip](https://github.com/bucanero/apollo-ps4/files/8526054/pack.2.savepatch.zip)

**Comment by bucanero** [comment]
added in #55
