### ISSUE TITLE
Add GTA 5 (PS4) custom decryption

### ISSUE THREAD

**Issue by bucanero** [bucanero/apollo-ps4#57]
based on feedback by ChendoChap:

```
dec = aes_dec_ecb("ps4 gta v save key", &data[0x114], __builtin_bswap32(*(int*)&data[0x108])));

// ps4 key is apparently the same key as ps3?
```

- if my comment is to be believed it's the same key as ps3 used? 
- aes encrypted blob starting at 0x114 with size as a big endian int at 0x108.

**Comment by bucanero** [comment]
```
:memory.dat

[AES Decrypt memory.dat (Required)]
set [end]:read(0x108,4)
set [end]:endian_swap
set range:0x000114,[end]
DECRYPT aes_ecb(0x1685FFA38D010F0DFE661CF9B5572C500D802648DB37B9ED0F48C57342C022F5)

[AES Encrypt memory.dat (Required)]
set [end]:read(0x108,4)
set [end]:endian_swap
set range:0x000114,[end]
ENCRYPT aes_ecb(0x1685FFA38D010F0DFE661CF9B5572C500D802648DB37B9ED0F48C57342C022F5)

```

**Comment by successorliver** [comment]
instruction on using it?

**Comment by bucanero** [comment]
> instruction on using it?

you need to open a GTA5 save-game (USB or HDD), CUSA00411 or CUSA00419. Then  the decrypt/encrypt codes will be loaded.

Only select the "decrypt" code, and apply changes. The `memory.dat` file custom encryption will be decrypted. Before you use the save in the game, you need to re-encrypt it. Select the encrypt option and apply changes.

This is only useful if you know how to modify the file data, or else you'll just turn you save invalid.
