### ISSUE TITLE
Save list improvements

### ISSUE THREAD

**Issue by leolapi4** [bucanero/apollo-ps4#59]
I don't really understand what the sort option does, but it never does what I've expected to.
I'd like to have saves ordered by CUSA number in reason to copy all of the saves related to that CUSA avoiding to search it within whole list.
It will be cool to have the structured list where in the top level you can see CUSA with the game name, maybe (obtained from local DB or some internet source) and when you enter the top level item you can see only the saves related to the item you have just entered into. And it also will be great if it will be able to copy all the saves related to the top level item at once.
I have also found some inconvenience in GUI. When I press up/down on the gamepad, it often seeks two items at one pressing. So I think you have to ignore the input buffer in one second (for instance) as you catch press button down until it will be pressed up and then clear the buffer to skip subsequential processing.
I beg you pardon if it partially mirrors an "Save listing requests #5". You can merge it then. Thank you!

**Comment by bucanero** [comment]
Save sorting options added in https://github.com/bucanero/apollo-ps4/commit/c416555a698b355b02140ea00f3a60b049261940

Improved pad controls added in https://github.com/bucanero/apollo-ps4/commit/78e5ada4eeb2d1b5a9b12672b57968bfa28f1a70
