### ISSUE TITLE
Trophy Unlocking?

### ISSUE THREAD

**Issue by subworx** [bucanero/apollo-ps4#6]
Will Apollo offer trophy unlocking?
Currently I can browse the games and specifically mark trophies as "select"ed, but cannot do anything to/with them except viewing the content.

**Comment by bucanero** [comment]
Currently there's no trophy unlocking support in Apollo. (the app is only listing un-synced trophy-sets)

It might be added in the future to keep the same features found in Apollo-PS3, but right now the priority is to add more save-game management features.
