### ISSUE TITLE
Save patches 

### ISSUE THREAD

**Issue by pauljames80** [bucanero/apollo-ps4#63]
Hi I noticed you were the one that added most of the save patches . There actually a lot of codes in the save wizard discord server. Here a invite link if you haven't joined already
https://discord.gg/tPGtpszHGK

Also this is a link of the spreadsheet archive of codes the save wizard community have made

https://docs.google.com/spreadsheets/d/1pln64WRA8QhhrW1QBDEn97HEbp4gdvBNd3GnrC4Bg5c

If you know which games don't have any extra encryption or compression I could help with save patches

**Comment by bucanero** [comment]
tagging @OfficialAhmed since he's been helping a lot with the Save wizard codes 👍

**Comment by pauljames80** [comment]
I accidentally contacted you instead of him I was in his fork of Apollo and I clicked issues I didn't realize it would post in your GitHub. I was able to send him a message on twitter

**Comment by OfficialAhmed** [comment]
Thanks @pauljames we’ll add them codes soon

**Comment by pauljames80** [comment]
I don't know if it's possible but one of the limitations of SW codes is you can't insert extra bytes only overwrite existing ones is it possible to create a new code type that could do that

**Comment by bucanero** [comment]
> I don't know if it's possible but one of the limitations of SW codes is you can't insert extra bytes only overwrite existing ones is it possible to create a new code type that could do that

Apollo also supports "BSD scripts", and that script has an `insert` command. For example:

```
[Max EXP code]
search "SomeDATA"
insert next (4):0x3939393939393939
```

that code will result in `Some99999999DATA`
