### ISSUE TITLE
Petición: borrar trofeos

### ISSUE THREAD

**Issue by arfgh** [bucanero/apollo-ps4#70]
Bucanero, sería genial que facilitases en la sección de trofeos la posibilidad de borrar todos los trofeos de un juego. Muchas veces queremos hacerlo porque hemos probado un juego que no vamos a volver a jugar porque no nos gusta o por lo que sea. Y lo tenemos ahí con 0 trofeos...

Pero recuerda que la carpeta sce_trop, también hay que borrarla para que la consola contabilice de nuevo los trofeos restantes. Y no estoy seguro del todo, de si habría que borrar también algunas líneas en la db de los trofeos.

Sea como sea, creo que sería una función importante y necesaria.

saludos

**Comment by bucanero** [comment]
keeping this request under #95
