### ISSUE TITLE
Frozen Controller using apollo tried reinstalling as well.

### ISSUE THREAD

**Issue by mrkingpin** [bucanero/apollo-ps4#71]
First time using your app today and after getting everything installed etc I am using latest golden hen 9.00 and installed apollo and also terminator resistance game save.

Playing the game for a few minutes the gun started autofiring on it's own and then just stopped firing completely.

Went to the apollo app and it had frozen so I closed the app rebooted ps4 to try again and when selecting apollo it just freezes again cant move or select anything.

I uninstalled the app and deleted the file it created in application saved data management then reinstalled the app but when it says it installed to press ok the controller is frozen and no buttons work except for the ps button to get to xmb menu.

I deleted any trace of the save game data .. tried reinstalling the app but it's still frozen and won't let me press ok to continue. Have tried cold booting the ps4 as well but still the app is crashing on install now.

UPDATE :

Ok for some reason the ps4 controller became buggy .. I deleted the game and the save data and removed apollo thinking that would help .. Nope same issue.

The controller even though working on xmb menu would not work in apollo app or in games.

Something happened to cause the ps4 controller to malfunction but resynced spare ps4 controller it's all working again. hopefully it doesnt happen again & still a bug worth looking at

**Comment by Masamune3210** [comment]
Try restarting ps4 completely. If app crashed, save patches probably were never removed which can screw things up

**Comment by Masamune3210** [comment]
Welp I should read better

**Comment by bucanero** [comment]
If it was a hardware issue with your controller then there's nothing related to Apollo or the game you were playing.

Also, always quit Apollo before launching another app or game, it really makes no sense or need to keep Apollo running. Doing this will leave less free memory to other games or apps and also the save game patches will remain applied in memory when they're not needed.
