### ISSUE TITLE
encrypted saves from hdd

### ISSUE THREAD

**Issue by Zhaxxy** [bucanero/apollo-ps4#76]
could you add a folder on the hdd where you can put ecnrpted usb saves so that you can copy saves from the internet directly to the console via ftp without having to plug in a usb

**Comment by Masamune3210** [comment]
perhaps say please or ask?

**Comment by illusion0001** [comment]
Made a special build that only reads from `/user/data/apollo/PS4/`.
tried implementing an option for it a while back but it crashed for some reason
https://github.com/illusion0001/apollo-ps4/releases/download/hdd/IV0000-APOL00004_00-APOLLO0000000PS4.pkg
![image](https://user-images.githubusercontent.com/37698908/204422422-4263ddc0-226b-4abc-a7d3-02fc13912cb4.png)
![image](https://user-images.githubusercontent.com/37698908/204422460-09a5f531-bf2f-42b3-9afb-8406a35c4349.png)

**Comment by illusion0001** [comment]
Fixed in #89
