### ISSUE TITLE
Some saves failed to be packaged, but SaveMounter can succeed.

### ISSUE THREAD

**Issue by ZACKhdn** [bucanero/apollo-ps4#79]
CUSA24705-Horizon Forbidden West
CUSA07182-LocoRoco Remastered
CUSA07183-LocoRoco 2 Remastered
CUSA07184-Patapon Remastered
CUSA08174-Patapon2 Remastered

These games use apollo to unpack to usb and then pack, then copy saves to genuine ps5, open game, can't find saves. But if I use SaveMounter and ftp, modify game save and copy it to genuine ps5, it can work normally.
I used apollo to modify hundreds of games and only found problems with these few games, I guess there's something wrong with package or sign.
I guess different regional versions of the same game have the same problem, I found different versions of the game at www.orbispatches.com, you can refer to.
（PS4:9.00+GoldHEN）

CUSA24705: CUSA28561/CUSA28563
CUSA07182: CUSA07286/CUSA06090
CUSA07183: CUSA06091/CUSA07695
CUSA07184: CUSA06171/CUSA09571/CUSA07285
CUSA08174: CUSA07321/CUSA07694

**Comment by bucanero** [comment]
I don't have any of those games, but I can take a look to the saves.

Can you upload decrypted saves from Apollo (not working) and save mounter (working) so I can compare the data files?

like the exact same save (export decrypted save with Apollo) , the non-working and the working versions. Maybe I can find some details while comparing files.

**Comment by bucanero** [comment]
I think this is the same issue as #98 (Apollo missed the param.sfo `SAVEDATA_LIST_PARAM` value)

**Comment by bucanero** [comment]
Can you test out this `.pkg` build, and see if transferring your saves work now?
https://github.com/bucanero/apollo-ps4/suites/10157426095/artifacts/496372357

**Comment by ZACKhdn** [comment]
I tested it and the problem is solved.
[#98](https://github.com/bucanero/apollo-ps4/issues/98#issuecomment-1370166956
)
