### ISSUE TITLE
Swap keystones

### ISSUE THREAD

**Issue by Buzbee** [bucanero/apollo-ps4#8]
Sometimes, I need to just swap keystones between the fake keystone and a retail keystone. It would be nice if it looked on usb for a filename by cusa and rename it to keystone and swap into save. For example, a file named cusa18886 on usb would be swapped and renamed for current keystone in cusa18886's save file. I have used this method with save mounter rather than exchange other contents and it works great as long as the save has not been already been flagged as corrupt already.

**Comment by bucanero** [comment]
For this feature, I'm thinking to export/import the `keystone` files to:
```
/data/apollo/<USER-ID>/CUSAxxxxx/keystone
```

that way it can be used for USB or HDD saves easily

**Comment by Buzbee** [comment]
sounds great

**Comment by bucanero** [comment]
Added in 69c4d7927bfdfcb50bed92e021b976be80534188
