### ISSUE TITLE
Consider making a documentation

### ISSUE THREAD

**Issue by LordLucass** [bucanero/apollo-ps4#84]
It would be interesting to have documentation explaining how the software functions are used, at least the main ones, and an example of how to modify the save. It is a good thing to do, considering that there is more demand from users who want to use this program but have no idea how to use it, or are afraid of doing things wrong.

**Comment by LordLucass** [comment]
Also, an example of how to install it, and what it requires at the time of installation is something that should not be overlooked.

**Comment by bucanero** [comment]
For general use, just search "apollo ps4" on Youtube and you'll find many videos explaining how to use the basic functionality (like transfer saves, copy, backup, +++)

Save-game editing/hacking is only recommended for experienced users. I suggest joining some Discord servers about save-game modding before attempting such hacks.

**Comment by LordLucass** [comment]
I understand that there are videos and some content about the tool, but most of them (if not all) are outdated, precisely because the development of the software is continuous, and an explanation directly from the developer or a contributor would be very good.

Also, what kind of Discord servers do you recommend to join to learn how to use Edit/Hack? 

I am new to this area, and would like to try it out, but I don't want to pay a Save Wizard without at least knowing a little about it and being able to use it correctly.

**Comment by bucanero** [comment]
You can start with https://discord.gg/save-wizard , many experienced users there. It's focused on Save Wizard but some users also have experience with Apollo and use both tools for save hacking.

**Comment by LordLucass** [comment]
I'm going to go into the room and get help. Thank you very much for your support and patience! I appreciate it, and your software seems to be a great alternative to Save Wizard for what it offers, keep up the development, it looks great. Cheers!

**Comment by LordLucass** [comment]
Closing now...
