### ISSUE TITLE
File couldn't be imported

### ISSUE THREAD

**Issue by BestDeveloper007** [bucanero/apollo-ps4#86]
Hello .. As I already wrote on a well-known forum, I have a problem with importing the saves of one game (CUSA09175, other games work). The problem is that this game increases the size of the save file during the game and then the import function does not work. When I start the new game, it has Blocks:96(size), my older saved position has Blocks:152(size). For this reason, the import is not possible.

The game works if I copy the entire save with manual copy, but I would have to always run Apollo and I really don't want that. Importing an older save for this game worked for me because it was same in size (96blocks, just like the new position), but with the last saved position, it's simply not possible due to the size(152blocks but can be more in future).

*1) Is it possible to fix it somehow? Alternatively, put a test button in the menu where I manually select the max save size in blocks (which I always know when I look at the save information). 

It didn't help even when I tried to copy the decrypted file to the correct folder via USB-PC... By that I mean that I create a new save, copy it to USB using Apollo. I replace the new one with old decrypted saves(backup from another profile) on the PC and then use Apollo to copy it to the HDD... -It didn't work like that with this game but it worked with another cusa game.

Ideas for improvements:
*2) Otherwise, I noticed that some games have long names and thus make the CUSA column impossible to read. It would be good to consider for example CUSA in a different color than the name of the game/position.

Thanks for reading, I believe these are simple things to fix that only take a few minutes.

**Comment by BestDeveloper007** [comment]
Solved with diffrent tool. In short: it was enough to create the same size save as the backup (152 blocks) via Save Mounter and insert the backup from Apollo into it via FTP. I verified it and the backup was the same size via apollo as via Save Mounter, so they work on a similar principle :)

**Comment by BestDeveloper007** [comment]
I solved the problem. The author of Apollo knows about the problem, so I'm closing.
Now it depends on the Author if he solves the problem and brings the program to perfection or continues as now with the Cheats section and other nonsense :D

**Comment by BestDeveloper007** [comment]
I solved the problem. The author of Apollo knows about the problem, so I'm closing.
Now it depends on the Author if he solves the problem and brings the program to perfection or continues as now with the Cheats section and other nonsense :D

**Comment by bucanero** [comment]
> I solved the problem. The author of Apollo knows about the problem, so I'm closing.
> 
> Now it depends on the Author if he solves the problem and brings the program to perfection or continues as now with the Cheats section and other nonsense :D

If you're so good at judging maybe you should be good at doing it yourself. Don't waste my time or use my tools if you can do it better.

**Comment by BestDeveloper007** [comment]
> If you're so good at judging maybe you should be good at doing it yourself. Don't waste my time or use my tools if you can do it better.

I'm sorry if I offended you. I can do it, it's easy, but I believe you can do it too.. I believe in your abilities.... overcome yourself, overcome your limits. I believe you can do it for others and you will have no excuses. Prove to yourself that you can do it.
