### ISSUE TITLE
Some issues after having activated a local user account

### ISSUE THREAD

**Issue by GitGitHubUser** [bucanero/apollo-ps4#9]
Hello @bucanero ,
I have a brand new PS4, now jailbroken with 9.0. Everything was excellent up to the point when I used "PSN offline activation" :-(. Now suddenly games start downloading updates (so I am in ban fear), in addition I can't use PS Remote Play anymore due to "user account mismatch" (was not a problem before). I guess because the faked PSN account ID is matched against my PSN account ID on the PC (it's a new PSN account without any games on it). Can I solve such problems now somehow without disabling the network entirely? :( (which I don't want to do due to many reasons) 
Maybe you can add "PSN deactivator" to deactivate my user account and stop all this from happening? Many thanks!!

**Comment by bucanero** [comment]
I'm not sure if a "deactivation" is possible or if it will work at all.
You might want to just remove the account and create a new one (leaving the new account de-activated)

If you want to change the account-id to another one, you can use ps4debug and the Account activator app on your PC, and just edit the account and change the id to some other ID. You might also want to try "000000000" as account-id, but again I'm not sure if it will work.

**Comment by GitGitHubUser** [comment]
Thanks, but as it was my only (primary) account I had to re-initialize the console... Maybe you should put a warning before letting people activate it that some unwanted side effects can happen unless the console is used strictly offline.
