### ISSUE TITLE
cusa24705 errors during savegame restore/import with encrypted and decrypted saves

### ISSUE THREAD

**Issue by FunThomas76** [bucanero/apollo-ps4#98]
Hi bucanero,
like i told in discord here again with tests and files. 
Starting of all is only one working save MANUALSAVE1 exists on PS4

01 start
working save backuped by system function and save mounter
renamed files from MANUALSAVE1 to MANUALSAVE2 on usb

02 
apollo started with "usb saves"
"copy save game to hdd" without resign
backup files with save mounter
delete savegame with system save management

03
apollo started with "usb saves"
"copy save game to hdd" with resign
backup files with save mounter
delete savegame with system save management

04 
renamed folder from decrypted save backup with save mounter from step1 to xxx_MANUALSAVE2 
and copied on usb stick, delete encrypted save
apollo started with "usb saves"
"copy save game to hdd"
MANUALSAVE1 was overwritten by apollo
backup files with save mounter
[saves.zip](https://github.com/bucanero/apollo-ps4/files/10327380/saves.zip)

saves from steps 02-04 do not show up in the game to load but in system save management

only the param.sfo is different when import saves

```
from step 01:  Adress A18: A9 F4 43 04 48 6F 72 69  ©ôCHori
from step 04:  Adress A18: 00 00 00 00 48 6F 72 69      Hori

```
Injecting with save mounter works fine

please tell me if more tests are needed

**Comment by bucanero** [comment]
thanks for sharing the saves and detailed steps. I'll review the saves when I have a chance. 👍

**Comment by bucanero** [comment]
from the `0x0A18` address, it seems that Apollo somehow missed the `SAVEDATA_LIST_PARAM` value. I'll check if something else shows up.

**Comment by ZACKhdn** [comment]
> @FunThomas76, the bug should be fixed now. You can test out this `.pkg` build: https://github.com/bucanero/apollo-ps4/suites/10157426095/artifacts/496372357
> 
> Let me know your results.

Whoa, it worked!!

I tested the following two games using the debug version
CUSA07182 - LocoRoco Remastered
CUSA07183 - LocoRoco 2 Remastered

Export saves to USB and pack it to HDD, then copy saves to PS5, everything works fine.
Bro, you did solve the problem.

**Comment by bucanero** [comment]
> Whoa, it worked!!
> 
> I tested the following two games using the debug version CUSA07182 - LocoRoco Remastered CUSA07183 - LocoRoco 2 Remastered
> 
> Export saves to USB and pack it to HDD, then copy saves to PS5, everything works fine. Bro, you did solve the problem.

thanks for the report, good to know everything is working now. 👍
